### PR TITLE
Fix units and descriptions in example project

### PR DESCRIPTION
**Pull request by fknipp**
The power is measured in kW, the energy in kWh.

Signed-off-by: Franz Knipp <franz@qnipp.com>

### CODE REVIEW

**Comment by cleancoderocker** [comment]
Before accepting the pull request, I just wanted to make sure: do you have an Eclipse account linked to the same email address used to submit the PR and have you filled out the "Eclipse Contributor Agreement" already?

Best regards,
Philip

**Comment by cleancoderocker** [comment]
Ah, wait. I just saw that this is part of the automatic checks 😊

**Comment by fknipp** [comment]
This PR did not find its way into version 2.3. Should I generate a PR against another branch instead of master?

**Comment by cleancoderocker** [comment]
I will check again. Probably it was "overwritten" again, because we also did some changes to the Windmill examples.

**Comment by anreinha** [comment]
The changes made it into the latest 2.3 version.

**Pull request merged**
